# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a42852d305f24579885aee4d4b5d6f5ec33cc3bdaca3b070b79d195322ccf2c6c9a7243c9777bea2ef73fdc32e6853d299bf1ab3cbf601ad16a445ec87a75fec

test:
  secret_key_base: f4169b9184200c917941cd2ab91e0fbd7f232ab49c73e0c586c5d2bc8d665e660e96b5f5cf603c18043c08fba9a8bd52b3a40a8cc31e5ddf973a78e2d9ea876a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
